# Batch Preprocessing

Run the finalized resting-state EEG preprocessing pipeline across all downloaded subjects.

## Setup

In [33]:
from importlib import reload
from pathlib import Path
import sys

import pandas as pd
from IPython.display import Markdown, display

project_root = Path.cwd().resolve()
if not (project_root / "src").exists():
    project_root = project_root.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

import src.eeg_utils as eeg_utils
import src.eeg_preprocessing as eeg_preprocessing

reload(eeg_utils)
reload(eeg_preprocessing)

data_root = project_root / "data" / "ds004796"
output_dir = project_root / "data" / "processed" / "eeg"

print(f"Project root: {project_root}")
print(f"Data root: {data_root}")
print(f"Output dir: {output_dir}")

Project root: /Users/nataliemarryatt/neurogenetics-ml
Data root: /Users/nataliemarryatt/neurogenetics-ml/data/ds004796
Output dir: /Users/nataliemarryatt/neurogenetics-ml/data/processed/eeg

## Find Subjects

In [5]:
vhdr_paths = eeg_preprocessing.find_rest_vhdrs(data_root)
subject_ids = [eeg_preprocessing.subject_id_from_vhdr(path) for path in vhdr_paths]

print(f"Found {len(subject_ids)} rest EEG files")
subject_ids

Found 78 rest EEG files

['sub-01',
 'sub-02',
 'sub-03',
 'sub-04',
 'sub-05',
 'sub-06',
 'sub-07',
 'sub-08',
 'sub-09',
 'sub-10',
 'sub-11',
 'sub-12',
 'sub-13',
 'sub-14',
 'sub-15',
 'sub-16',
 'sub-17',
 'sub-18',
 'sub-19',
 'sub-20',
 'sub-21',
 'sub-22',
 'sub-23',
 'sub-24',
 'sub-25',
 'sub-26',
 'sub-27',
 'sub-28',
 'sub-29',
 'sub-30',
 'sub-31',
 'sub-32',
 'sub-33',
 'sub-34',
 'sub-35',
 'sub-36',
 'sub-37',
 'sub-38',
 'sub-39',
 'sub-40',
 'sub-41',
 'sub-42',
 'sub-43',
 'sub-44',
 'sub-45',
 'sub-46',
 'sub-47',
 'sub-48',
 'sub-49',
 'sub-50',
 'sub-51',
 'sub-52',
 'sub-53',
 'sub-54',
 'sub-56',
 'sub-57',
 'sub-58',
 'sub-59',
 'sub-60',
 'sub-61',
 'sub-62',
 'sub-63',
 'sub-64',
 'sub-65',
 'sub-66',
 'sub-67',
 'sub-68',
 'sub-70',
 'sub-71',
 'sub-72',
 'sub-73',
 'sub-74',
 'sub-75',
 'sub-76',
 'sub-77',
 'sub-78',
 'sub-79',
 'sub-80']

## Optional Smoke Test

In [6]:
# Optional dry run: confirms the batch function works without writing files.
test_results, test_run_qc = eeg_preprocessing.preprocess_all_rest_subjects(
    data_root=data_root,
    output_dir=None,
    save_epochs=False,
    subject_ids=subject_ids[:1],
    continue_on_error=True,
    use_icalabel=True,
    ica_n_components=None,
)
test_run_qc

Extracting parameters from /Users/nataliemarryatt/neurogenetics-ml/data/ds004796/sub-01/eeg/sub-01_task-rest_eeg.vhdr...
Setting channel info structure...
Reading 0 ... 661519  =      0.000 ...   661.519 secs...
Filtering raw data in 1 contiguous segment
Removed notch frequencies (Hz):
     50.00 : 5969 windows
Setting up high-pass filter at 1 Hz

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal highpass filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower passband edge: 1.00
- Lower transition bandwidth: 1.00 Hz (-6 dB cutoff frequency: 0.50 Hz)
- Filter length: 825 samples (3.300 s)

Executing RANSAC
This may take a while, so be patient...

  0%|          |  : 0/48 [00:00<?,       ?it/s]

RANSAC done!

2026-08-16 22:20:51,247 - pyprep.reference - INFO - Bad channels: {'bad_by_nan': [], 'bad_by_flat': [], 'bad_by_deviation': [], 'bad_by_hf_noise': ['FCC6h'], 'bad_by_correlation': ['Cz', 'FC2', 'FFC1h', 'FFC2h', 'FCC1h', 'FCC2h'], 'bad_by_SNR': [], 'bad_by_dropout': [], 'bad_by_psd': ['AF4', 'TPP9h', 'AFF6h'], 'bad_by_ransac': [], 'bad_by_manual': [], 'bad_all': ['FCC2h', 'TPP9h', 'AFF6h', 'FC2', 'FCC1h', 'FFC1h', 'Cz', 'FCC6h', 'FFC2h', 'AF4']}

Executing RANSAC
This may take a while, so be patient...

  0%|          |  : 0/48 [00:00<?,       ?it/s]

RANSAC done!

2026-08-16 22:20:57,731 - pyprep.reference - INFO - Bad channels: {'bad_by_nan': [], 'bad_by_flat': [], 'bad_by_deviation': ['AF4'], 'bad_by_hf_noise': [], 'bad_by_correlation': ['TP10', 'F4', 'TP9'], 'bad_by_SNR': [], 'bad_by_dropout': [], 'bad_by_psd': ['AFF6h', 'Fp2', 'AF7', 'AFp2', 'Fp1', 'AF8', 'AF4'], 'bad_by_ransac': [np.str_('TPP9h')], 'bad_by_manual': [], 'bad_all': ['TP10', 'F4', 'AFF6h', 'TP9', np.str_('TPP9h'), 'Fp2', 'AF7', 'AFp2', 'Fp1', 'AF8', 'AF4']}

Setting channel interpolation method to {'eeg': 'spline'}.
Interpolating bad channels.
    Automatic origin fit: head of radius 95.0 mm
Computing interpolation matrix from 116 sensor positions
Interpolating 11 sensors

2026-08-16 22:20:57,795 - pyprep.reference - INFO - Iterations: 1

Executing RANSAC
This may take a while, so be patient...

  0%|          |  : 0/48 [00:00<?,       ?it/s]

RANSAC done!

2026-08-16 22:21:03,902 - pyprep.reference - INFO - Bad channels: {'bad_by_nan': [], 'bad_by_flat': [], 'bad_by_deviation': ['Fp1', 'AFF6h', 'AF4', 'Fp2'], 'bad_by_hf_noise': [], 'bad_by_correlation': ['TP10', 'F4', 'AFF6h', 'TP9', 'Fp1'], 'bad_by_SNR': [], 'bad_by_dropout': [], 'bad_by_psd': ['AFF6h', 'AFp1', 'Fp2', 'AF7', 'AFp2', 'Fp1', 'AF8', 'AF4'], 'bad_by_ransac': [np.str_('TPP9h'), np.str_('FTT8h')], 'bad_by_manual': [], 'bad_all': ['TP10', 'F4', 'AFF6h', 'TP9', 'AFp1', 'Fp2', 'AF7', np.str_('TPP9h'), np.str_('FTT8h'), 'AFp2', 'Fp1', 'AF8', 'AF4']}

Setting channel interpolation method to {'eeg': 'spline'}.
Interpolating bad channels.
    Automatic origin fit: head of radius 95.0 mm
Computing interpolation matrix from 114 sensor positions
Interpolating 13 sensors

2026-08-16 22:21:03,961 - pyprep.reference - INFO - Iterations: 2

Executing RANSAC
This may take a while, so be patient...

  0%|          |  : 0/48 [00:00<?,       ?it/s]

RANSAC done!

2026-08-16 22:21:10,046 - pyprep.reference - INFO - Bad channels: {'bad_by_nan': [], 'bad_by_flat': [], 'bad_by_deviation': ['Fp1', 'AFF6h', 'AF4', 'Fp2'], 'bad_by_hf_noise': [], 'bad_by_correlation': ['TP10', 'F4', 'AFF6h', 'TP9', 'Fp1'], 'bad_by_SNR': [], 'bad_by_dropout': [], 'bad_by_psd': ['AFp1', 'AFF6h', 'Fp2', 'AF7', 'AFp2', 'Fp1', 'AF8', 'AF4'], 'bad_by_ransac': [np.str_('TPP9h'), np.str_('FTT8h')], 'bad_by_manual': [], 'bad_all': ['TP10', 'F4', 'AFF6h', 'TP9', 'AFp1', 'Fp2', 'AF7', np.str_('TPP9h'), np.str_('FTT8h'), 'AFp2', 'Fp1', 'AF8', 'AF4']}
2026-08-16 22:21:10,047 - pyprep.reference - INFO - Robust reference done

Setting channel interpolation method to {'eeg': 'spline'}.
Interpolating bad channels.
    Automatic origin fit: head of radius 95.0 mm
Computing interpolation matrix from 114 sensor positions
Interpolating 13 sensors
Setting up high-pass filter at 1 Hz

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal highpass filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower passband edge: 1.00
- Lower transition bandwidth: 1.00 Hz (-6 dB cutoff frequency: 0.50 Hz)
- Filter length: 825 samples (3.300 s)

Executing RANSAC
This may take a while, so be patient...

  0%|          |  : 0/48 [00:00<?,       ?it/s]

RANSAC done!
Found 12 uniquely bad channels:

0 by NaN: []

0 by flat: []

4 by deviation: ['Fp1', 'Fp2', 'AF4', 'AFF6h']

0 by HF noise: []

5 by correlation: ['Fp1', 'TP9', 'TP10', 'F4', 'AFF6h']

0 by SNR: []

0 by dropout: []

8 by PSD: ['Fp1', 'Fp2', 'AF7', 'AF8', 'AF4', 'AFp1', 'AFF6h', 'AFp2']

1 by RANSAC: [np.str_('FTT8h')]

0 by manual: []

Setting channel interpolation method to {'eeg': 'spline'}.
Interpolating bad channels.
    Automatic origin fit: head of radius 95.0 mm
Computing interpolation matrix from 115 sensor positions
Interpolating 12 sensors
Setting up high-pass filter at 1 Hz

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal highpass filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower passband edge: 1.00
- Lower transition bandwidth: 1.00 Hz (-6 dB cutoff frequency: 0.50 Hz)
- Filter length: 825 samples (3.300 s)

Executing RANSAC
This may take a while, so be patient...

  0%|          |  : 0/48 [00:00<?,       ?it/s]

RANSAC done!
Filtering raw data in 1 contiguous segment
Setting up band-pass filter from 1 - 40 Hz

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandpass filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower passband edge: 1.00
- Lower transition bandwidth: 1.00 Hz (-6 dB cutoff frequency: 0.50 Hz)
- Upper passband edge: 40.00 Hz
- Upper transition bandwidth: 10.00 Hz (-6 dB cutoff frequency: 45.00 Hz)
- Filter length: 825 samples (3.300 s)

Fitting ICA to data using 124 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 114 components
Fitting ICA took 9.0s.
Using EOG channel: Fp1
... filtering ICA sources
Setting up band-pass filter from 1 - 10 Hz

FIR filter parameters
---------------------
Designing a two-pass forward and reverse, zero-phase, non-causal bandpass filter:
- Windowed frequency-domain design (firwin2) method
- Hann window
- Lower passband edge: 1.00
- Lower transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 0.75 Hz)
- Upper passband edge: 10.00 Hz
- Upper transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 10.25 Hz)
- Filter length: 2500 samples (10.000 s)

... filtering target
Setting up band-pass filter from 1 - 10 Hz

FIR filter parameters
---------------------
Designing a two-pass forward and reverse, zero-phase, non-causal bandpass filter:
- Windowed frequency-domain design (firwin2) method
- Hann window
- Lower passband edge: 1.00
- Lower transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 0.75 Hz)
- Upper passband edge: 10.00 Hz
- Upper transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 10.25 Hz)
- Filter length: 2500 samples (10.000 s)

Using EOG channel: Fp2
... filtering ICA sources
Setting up band-pass filter from 1 - 10 Hz

FIR filter parameters
---------------------
Designing a two-pass forward and reverse, zero-phase, non-causal bandpass filter:
- Windowed frequency-domain design (firwin2) method
- Hann window
- Lower passband edge: 1.00
- Lower transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 0.75 Hz)
- Upper passband edge: 10.00 Hz
- Upper transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 10.25 Hz)
- Filter length: 2500 samples (10.000 s)

... filtering target
Setting up band-pass filter from 1 - 10 Hz

FIR filter parameters
---------------------
Designing a two-pass forward and reverse, zero-phase, non-causal bandpass filter:
- Windowed frequency-domain design (firwin2) method
- Hann window
- Lower passband edge: 1.00
- Lower transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 0.75 Hz)
- Upper passband edge: 10.00 Hz
- Upper transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 10.25 Hz)
- Filter length: 2500 samples (10.000 s)

Using EOG channel: AFp1
... filtering ICA sources
Setting up band-pass filter from 1 - 10 Hz

FIR filter parameters
---------------------
Designing a two-pass forward and reverse, zero-phase, non-causal bandpass filter:
- Windowed frequency-domain design (firwin2) method
- Hann window
- Lower passband edge: 1.00
- Lower transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 0.75 Hz)
- Upper passband edge: 10.00 Hz
- Upper transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 10.25 Hz)
- Filter length: 2500 samples (10.000 s)

... filtering target
Setting up band-pass filter from 1 - 10 Hz

FIR filter parameters
---------------------
Designing a two-pass forward and reverse, zero-phase, non-causal bandpass filter:
- Windowed frequency-domain design (firwin2) method
- Hann window
- Lower passband edge: 1.00
- Lower transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 0.75 Hz)
- Upper passband edge: 10.00 Hz
- Upper transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 10.25 Hz)
- Filter length: 2500 samples (10.000 s)

Using EOG channel: AFp2
... filtering ICA sources
Setting up band-pass filter from 1 - 10 Hz

FIR filter parameters
---------------------
Designing a two-pass forward and reverse, zero-phase, non-causal bandpass filter:
- Windowed frequency-domain design (firwin2) method
- Hann window
- Lower passband edge: 1.00
- Lower transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 0.75 Hz)
- Upper passband edge: 10.00 Hz
- Upper transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 10.25 Hz)
- Filter length: 2500 samples (10.000 s)

... filtering target
Setting up band-pass filter from 1 - 10 Hz

FIR filter parameters
---------------------
Designing a two-pass forward and reverse, zero-phase, non-causal bandpass filter:
- Windowed frequency-domain design (firwin2) method
- Hann window
- Lower passband edge: 1.00
- Lower transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 0.75 Hz)
- Upper passband edge: 10.00 Hz
- Upper transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 10.25 Hz)
- Filter length: 2500 samples (10.000 s)

/Users/nataliemarryatt/neurogenetics-ml/src/eeg_preprocessing.py:140: RuntimeWarning: The provided Raw instance does not seem to be referenced to a common average reference (CAR). ICLabel was designed to classify features extracted from an EEG dataset referenced to a CAR (see the 'set_eeg_reference()' method for Raw and Epochs instances).
  labels = label_components(raw, ica, method="iclabel")
/Users/nataliemarryatt/neurogenetics-ml/src/eeg_preprocessing.py:140: RuntimeWarning: The provided Raw instance is not filtered between 1 and 100 Hz. ICLabel was designed to classify features extracted from an EEG dataset bandpass filtered between 1 and 100 Hz (see the 'filter()' method for Raw and Epochs instances).
  labels = label_components(raw, ica, method="iclabel")
/Users/nataliemarryatt/neurogenetics-ml/src/eeg_preprocessing.py:140: RuntimeWarning: The provided ICA instance was fitted with a 'fastica' algorithm. ICLabel was designed with extended infomax ICA decompositions. To use the extended infomax algorithm, use the 'mne.preprocessing.ICA' instance with the arguments 'ICA(method='infomax', fit_params=dict(extended=True))' (scikit-learn) or 'ICA(method='picard', fit_params=dict(ortho=False, extended=True))' (python-picard).
  labels = label_components(raw, ica, method="iclabel")

Applying ICA to Raw instance
    Transforming to ICA space (114 components)
    Zeroing out 10 ICA components
    Projecting back using 124 PCA components
Not setting metadata
120 matching events found
No baseline correction applied
0 projection items activated
Using data from preloaded Raw for 120 events and 500 original time points ...
0 bad epochs dropped
    Rejecting  epoch based on EEG : ['F3', 'F7', 'FC5', 'FC6', 'F8', 'F5', 'FC3', 'FC4', 'F6', 'AF8', 'F9', 'FFC5h', 'FFC6h', 'AFF5h', 'FFT9h', 'FFT7h', 'FCC5h', 'FFT8h']
1 bad epochs dropped
Filtering raw data in 1 contiguous segment
Removed notch frequencies (Hz):
     50.00 : 9017 windows
Setting up high-pass filter at 1 Hz

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal highpass filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower passband edge: 1.00
- Lower transition bandwidth: 1.00 Hz (-6 dB cutoff frequency: 0.50 Hz)
- Filter length: 825 samples (3.300 s)

Executing RANSAC
This may take a while, so be patient...

  0%|          |  : 0/72 [00:00<?,       ?it/s]

RANSAC done!

2026-08-16 22:21:56,807 - pyprep.reference - INFO - Bad channels: {'bad_by_nan': [], 'bad_by_flat': [], 'bad_by_deviation': [], 'bad_by_hf_noise': [], 'bad_by_correlation': ['Cz', 'FFC2h', 'FCC2h'], 'bad_by_SNR': [], 'bad_by_dropout': [], 'bad_by_psd': [], 'bad_by_ransac': [], 'bad_by_manual': [], 'bad_all': ['FCC2h', 'FFC2h', 'Cz']}

Executing RANSAC
This may take a while, so be patient...

  0%|          |  : 0/72 [00:00<?,       ?it/s]

RANSAC done!

2026-08-16 22:22:06,805 - pyprep.reference - INFO - Bad channels: {'bad_by_nan': [], 'bad_by_flat': [], 'bad_by_deviation': [], 'bad_by_hf_noise': [], 'bad_by_correlation': ['TP10', 'Fp1'], 'bad_by_SNR': [], 'bad_by_dropout': [], 'bad_by_psd': ['TP10', 'TP9', 'AFp1', 'TPP9h', 'AF3', 'AFF6h', 'Fp1', 'AFF5h', 'P5', 'AF4'], 'bad_by_ransac': [], 'bad_by_manual': [], 'bad_all': ['TP10', 'TP9', 'AFp1', 'TPP9h', 'AF3', 'AFF6h', 'Fp1', 'AFF5h', 'P5', 'AF4']}

Setting channel interpolation method to {'eeg': 'spline'}.
Interpolating bad channels.
    Automatic origin fit: head of radius 95.0 mm
Computing interpolation matrix from 117 sensor positions
Interpolating 10 sensors

2026-08-16 22:22:06,887 - pyprep.reference - INFO - Iterations: 1

Executing RANSAC
This may take a while, so be patient...

  0%|          |  : 0/72 [00:00<?,       ?it/s]

RANSAC done!

2026-08-16 22:22:16,454 - pyprep.reference - INFO - Bad channels: {'bad_by_nan': [], 'bad_by_flat': [], 'bad_by_deviation': [], 'bad_by_hf_noise': [], 'bad_by_correlation': ['TP10', 'Fp1'], 'bad_by_SNR': [], 'bad_by_dropout': [], 'bad_by_psd': ['TP10', 'TP9', 'AFp1', 'TPP9h', 'AF3', 'AFF6h', 'Fp1', 'AFF5h', 'P5', 'AF4'], 'bad_by_ransac': [np.str_('AF4')], 'bad_by_manual': [], 'bad_all': ['TP10', 'TP9', 'AFp1', 'TPP9h', 'AF3', 'AFF6h', 'Fp1', 'AFF5h', 'P5', 'AF4']}

Setting channel interpolation method to {'eeg': 'spline'}.
Interpolating bad channels.
    Automatic origin fit: head of radius 95.0 mm
Computing interpolation matrix from 117 sensor positions
Interpolating 10 sensors

2026-08-16 22:22:16,531 - pyprep.reference - INFO - Iterations: 2

Executing RANSAC
This may take a while, so be patient...

  0%|          |  : 0/72 [00:00<?,       ?it/s]

RANSAC done!

2026-08-16 22:22:26,153 - pyprep.reference - INFO - Bad channels: {'bad_by_nan': [], 'bad_by_flat': [], 'bad_by_deviation': [], 'bad_by_hf_noise': [], 'bad_by_correlation': ['TP10', 'Fp1'], 'bad_by_SNR': [], 'bad_by_dropout': [], 'bad_by_psd': ['TP10', 'TP9', 'AFp1', 'TPP9h', 'AF3', 'AFF6h', 'Fp1', 'AFF5h', 'P5', 'AF4'], 'bad_by_ransac': [np.str_('Fp1'), np.str_('AF4')], 'bad_by_manual': [], 'bad_all': ['TP10', 'TP9', 'AFp1', 'TPP9h', 'AF3', 'AFF6h', 'Fp1', 'AFF5h', 'P5', 'AF4']}
2026-08-16 22:22:26,154 - pyprep.reference - INFO - Robust reference done

Setting channel interpolation method to {'eeg': 'spline'}.
Interpolating bad channels.
    Automatic origin fit: head of radius 95.0 mm
Computing interpolation matrix from 117 sensor positions
Interpolating 10 sensors
Setting up high-pass filter at 1 Hz

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal highpass filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower passband edge: 1.00
- Lower transition bandwidth: 1.00 Hz (-6 dB cutoff frequency: 0.50 Hz)
- Filter length: 825 samples (3.300 s)

Executing RANSAC
This may take a while, so be patient...

  0%|          |  : 0/72 [00:00<?,       ?it/s]

RANSAC done!
Found 8 uniquely bad channels:

0 by NaN: []

0 by flat: []

0 by deviation: []

0 by HF noise: []

1 by correlation: ['TP10']

0 by SNR: []

0 by dropout: []

8 by PSD: ['Fp1', 'TP10', 'AF3', 'AF4', 'AFp1', 'AFF5h', 'TPP9h', 'AFF6h']

0 by RANSAC: []

0 by manual: []

Setting channel interpolation method to {'eeg': 'spline'}.
Interpolating bad channels.
    Automatic origin fit: head of radius 95.0 mm
Computing interpolation matrix from 119 sensor positions
Interpolating 8 sensors
Setting up high-pass filter at 1 Hz

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal highpass filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower passband edge: 1.00
- Lower transition bandwidth: 1.00 Hz (-6 dB cutoff frequency: 0.50 Hz)
- Filter length: 825 samples (3.300 s)

Executing RANSAC
This may take a while, so be patient...

  0%|          |  : 0/72 [00:00<?,       ?it/s]

RANSAC done!
Filtering raw data in 1 contiguous segment
Setting up band-pass filter from 1 - 40 Hz

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandpass filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower passband edge: 1.00
- Lower transition bandwidth: 1.00 Hz (-6 dB cutoff frequency: 0.50 Hz)
- Upper passband edge: 40.00 Hz
- Upper transition bandwidth: 10.00 Hz (-6 dB cutoff frequency: 45.00 Hz)
- Filter length: 825 samples (3.300 s)

Fitting ICA to data using 122 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 117 components
Fitting ICA took 22.4s.
Using EOG channel: Fp1
... filtering ICA sources
Setting up band-pass filter from 1 - 10 Hz

FIR filter parameters
---------------------
Designing a two-pass forward and reverse, zero-phase, non-causal bandpass filter:
- Windowed frequency-domain design (firwin2) method
- Hann window
- Lower passband edge: 1.00
- Lower transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 0.75 Hz)
- Upper passband edge: 10.00 Hz
- Upper transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 10.25 Hz)
- Filter length: 2500 samples (10.000 s)

... filtering target
Setting up band-pass filter from 1 - 10 Hz

FIR filter parameters
---------------------
Designing a two-pass forward and reverse, zero-phase, non-causal bandpass filter:
- Windowed frequency-domain design (firwin2) method
- Hann window
- Lower passband edge: 1.00
- Lower transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 0.75 Hz)
- Upper passband edge: 10.00 Hz
- Upper transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 10.25 Hz)
- Filter length: 2500 samples (10.000 s)

Using EOG channel: Fp2
... filtering ICA sources
Setting up band-pass filter from 1 - 10 Hz

FIR filter parameters
---------------------
Designing a two-pass forward and reverse, zero-phase, non-causal bandpass filter:
- Windowed frequency-domain design (firwin2) method
- Hann window
- Lower passband edge: 1.00
- Lower transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 0.75 Hz)
- Upper passband edge: 10.00 Hz
- Upper transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 10.25 Hz)
- Filter length: 2500 samples (10.000 s)

... filtering target
Setting up band-pass filter from 1 - 10 Hz

FIR filter parameters
---------------------
Designing a two-pass forward and reverse, zero-phase, non-causal bandpass filter:
- Windowed frequency-domain design (firwin2) method
- Hann window
- Lower passband edge: 1.00
- Lower transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 0.75 Hz)
- Upper passband edge: 10.00 Hz
- Upper transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 10.25 Hz)
- Filter length: 2500 samples (10.000 s)

Using EOG channel: AFp1
... filtering ICA sources
Setting up band-pass filter from 1 - 10 Hz

FIR filter parameters
---------------------
Designing a two-pass forward and reverse, zero-phase, non-causal bandpass filter:
- Windowed frequency-domain design (firwin2) method
- Hann window
- Lower passband edge: 1.00
- Lower transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 0.75 Hz)
- Upper passband edge: 10.00 Hz
- Upper transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 10.25 Hz)
- Filter length: 2500 samples (10.000 s)

... filtering target
Setting up band-pass filter from 1 - 10 Hz

FIR filter parameters
---------------------
Designing a two-pass forward and reverse, zero-phase, non-causal bandpass filter:
- Windowed frequency-domain design (firwin2) method
- Hann window
- Lower passband edge: 1.00
- Lower transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 0.75 Hz)
- Upper passband edge: 10.00 Hz
- Upper transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 10.25 Hz)
- Filter length: 2500 samples (10.000 s)

Using EOG channel: AFp2
... filtering ICA sources
Setting up band-pass filter from 1 - 10 Hz

FIR filter parameters
---------------------
Designing a two-pass forward and reverse, zero-phase, non-causal bandpass filter:
- Windowed frequency-domain design (firwin2) method
- Hann window
- Lower passband edge: 1.00
- Lower transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 0.75 Hz)
- Upper passband edge: 10.00 Hz
- Upper transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 10.25 Hz)
- Filter length: 2500 samples (10.000 s)

... filtering target
Setting up band-pass filter from 1 - 10 Hz

FIR filter parameters
---------------------
Designing a two-pass forward and reverse, zero-phase, non-causal bandpass filter:
- Windowed frequency-domain design (firwin2) method
- Hann window
- Lower passband edge: 1.00
- Lower transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 0.75 Hz)
- Upper passband edge: 10.00 Hz
- Upper transition bandwidth: 0.50 Hz (-12 dB cutoff frequency: 10.25 Hz)
- Filter length: 2500 samples (10.000 s)

/Users/nataliemarryatt/neurogenetics-ml/src/eeg_preprocessing.py:140: RuntimeWarning: The provided Raw instance does not seem to be referenced to a common average reference (CAR). ICLabel was designed to classify features extracted from an EEG dataset referenced to a CAR (see the 'set_eeg_reference()' method for Raw and Epochs instances).
  labels = label_components(raw, ica, method="iclabel")
/Users/nataliemarryatt/neurogenetics-ml/src/eeg_preprocessing.py:140: RuntimeWarning: The provided Raw instance is not filtered between 1 and 100 Hz. ICLabel was designed to classify features extracted from an EEG dataset bandpass filtered between 1 and 100 Hz (see the 'filter()' method for Raw and Epochs instances).
  labels = label_components(raw, ica, method="iclabel")
/Users/nataliemarryatt/neurogenetics-ml/src/eeg_preprocessing.py:140: RuntimeWarning: The provided ICA instance was fitted with a 'fastica' algorithm. ICLabel was designed with extended infomax ICA decompositions. To use the extended infomax algorithm, use the 'mne.preprocessing.ICA' instance with the arguments 'ICA(method='infomax', fit_params=dict(extended=True))' (scikit-learn) or 'ICA(method='picard', fit_params=dict(ortho=False, extended=True))' (python-picard).
  labels = label_components(raw, ica, method="iclabel")

Applying ICA to Raw instance
    Transforming to ICA space (117 components)
    Zeroing out 11 ICA components
    Projecting back using 122 PCA components
Not setting metadata
180 matching events found
No baseline correction applied
0 projection items activated
Using data from preloaded Raw for 180 events and 500 original time points ...
0 bad epochs dropped
    Rejecting  epoch based on EEG : ['F7', 'FT9', 'C3', 'C4', 'T8', 'FT10', 'FC6', 'F8', 'Fp2', 'FT7', 'FC3', 'C6', 'AF8', 'F9', 'FFC5h', 'FTT7h', 'FCC3h', 'CCP6h', 'FTT8h', 'FFC6h', 'F10', 'FFT9h', 'FFT7h', 'FCC5h', 'FTT9h', 'TTP8h', 'FTT10h', 'FCC6h', 'FFT8h', 'FFT10h']
1 bad epochs dropped

  subject_id status error
0     sub-01     ok

## Run Batch / Resume Missing Subjects

By default, this cell resumes the batch by processing only missing or partial subjects. Set `run_all=True` only when you intentionally want to reprocess every subject and overwrite saved outputs.

In [32]:
# Default: resume from missing/partial subjects only.
# Set run_all=True only when you intentionally want to reprocess every subject from scratch.
results, run_qc = eeg_preprocessing.preprocess_all_rest_subjects(
    data_root=data_root,
    output_dir=output_dir,
    subject_ids=None,
    continue_on_error=True,
    run_all=False,
    use_icalabel=True,
    ica_n_components=None,
)

run_qc

Extracting parameters from /Users/nataliemarryatt/neurogenetics-ml/data/ds004796/sub-19/eeg/sub-19_task-rest_eeg.vhdr...
Setting channel info structure...
Reading 0 ... 617739  =      0.000 ...   617.739 secs...
Extracting parameters from /Users/nataliemarryatt/neurogenetics-ml/data/ds004796/sub-30/eeg/sub-30_task-rest_eeg.vhdr...
Setting channel info structure...
Reading 0 ... 628839  =      0.000 ...   628.839 secs...
Extracting parameters from /Users/nataliemarryatt/neurogenetics-ml/data/ds004796/sub-34/eeg/sub-34_task-rest_eeg.vhdr...
Setting channel info structure...
Reading 0 ... 726079  =      0.000 ...   726.079 secs...

   subject_id status error    status_this_run error_this_run
0      sub-01     ok        already_processed
1      sub-02     ok        already_processed
2      sub-03     ok        already_processed
3      sub-04     ok        already_processed
4      sub-05     ok        already_processed
..        ...    ...   ...                ...            ...
73     sub-76     ok        already_processed
74     sub-77     ok        already_processed
75     sub-78     ok        already_processed
76     sub-79     ok        already_processed
77     sub-80     ok        already_processed

[78 rows x 5 columns]

## Review QC Outputs

In [30]:
# Rebuild aggregate QC from saved per-subject files.
# This works after a kernel restart and does not require the original in-memory results object.
qc = eeg_preprocessing.rebuild_rest_preprocessing_qc(output_dir, data_root=data_root)

run_qc = qc["run_qc"]
prep_qc = qc["prep_qc"]
ica_qc = qc["ica_qc"]
epoch_qc = qc["epoch_qc"]

qc_review_tables = eeg_preprocessing.make_qc_review_tables(run_qc, prep_qc, ica_qc, epoch_qc)
ica_qc_compact = qc_review_tables["ica_compact"]

# Notebook display stays compact; full tables are saved to disk by rebuild_rest_preprocessing_qc().
incomplete_qc = run_qc.loc[run_qc["status"].isin(["missing", "partial", "error"])].copy()

display(Markdown("### Overall QC: missing, partial, or error only"))
display(incomplete_qc)

display(Markdown("### PREP QC: top 20 still-noisy rows"))
display(qc_review_tables["prep_most_noisy"].head(20))

display(Markdown("### ICA QC: top 20 rows by removed components"))
display(qc_review_tables["ica_most_removed"].head(20))

display(Markdown("### Epoch QC: top 20 rows by rejected epochs"))
display(qc_review_tables["epoch_most_rejected"].head(20))

print(f"Full aggregate QC tables saved in: {output_dir}")

### Overall QC: missing, partial, or error only

   subject_id   status error
18     sub-19  missing
29     sub-30  missing
33     sub-34  missing

### PREP QC: top 20 still-noisy rows

,subject_id,condition,n_still_noisy_channels,still_noisy_channels,n_interpolated_channels,interpolated_channels
64,sub-36,eyes_open,10,"['TP10', 'TPP9h', 'FFC5h', 'PO9', 'AFp2', 'TP8', 'F5', 'P9', 'FT9', 'PPO9h']",21,"['AFp1', 'AF7', 'FFT7h', 'T8', 'TP9', 'AFF6h', 'F6', 'P10', 'PO7', 'FT10', 'AF4', 'F4', 'Fp2', 'P9', 'FTT7h', 'CP5',..."
56,sub-31,eyes_open,10,"['TPP10h', 'AF3', 'AF7', 'FTT10h', 'F8', 'P10', 'FFT9h', 'PO7', 'POO9h', 'P8']",12,"['F9', 'TP9', 'AFF6h', 'Fp2', 'F6', 'FFC6h', 'AFp2', 'Fp1', 'AFF5h', 'AF8', 'PPO10h', 'AF4']"
106,sub-58,eyes_open,9,"['F4', 'AFF6h', 'AFp1', 'Fp2', 'FFT7h', 'F3', 'Fp1', 'AFp2', 'F5']",18,"['FTT7h', 'AFp1', 'AF3', 'Fp2', 'AF7', 'F6', 'FTT10h', 'F7', 'FFC5h', 'FT7', 'AFp2', 'Fp1', 'FFT10h', 'AFF5h', 'AF8'..."
22,sub-12,eyes_open,8,"['FCC2h', 'AFF6h', 'AFp1', 'Fp2', 'AF7', 'AFp2', 'Fp1', 'AF8']",22,"['TP10', 'FFT7h', 'FFT8h', 'PPO10h', 'F5', 'FFT9h', 'F6', 'P10', 'FC5', 'FTT9h', 'FT9', 'T7', 'F9', 'TPP10h', 'AF3',..."
138,sub-75,eyes_open,8,"['PO9', 'OI1h', 'F5', 'P9', 'O9', 'POO9h', 'O1', 'PO7']",20,"['TP9', 'TTP8h', 'P9', 'FFT7h', 'AF7', 'CP5', 'FTT9h', 'AFF6h', 'AF4', 'AFF5h', 'FCC5h', 'FT7', 'PPO9h', 'PO9', 'FTT..."
122,sub-66,eyes_open,8,"['T7', 'FTT9h', 'FFC3h', 'FC3', 'AFF6h', 'FFT8h', 'F1', 'FCC5h']",7,"['Cz', 'FFC5h', 'F3', 'FC6', 'Fp1', 'FFC6h', 'FCC1h']"
77,sub-42,eyes_closed,7,"['F9', 'TP9', 'AFp1', 'AFz', 'FFT9h', 'FTT9h', 'FT9']",32,"['FC6', 'POz', 'FFT7h', 'FFT8h', 'PO4', 'PPO10h', 'T8', 'FCC6h', 'CPP6h', 'OI2h', 'CP6', 'CP1', 'PO10', 'FTT8h', 'PP..."
14,sub-08,eyes_open,7,"['TP10', 'CCP3h', 'C1', 'F7', 'FCC3h', 'FFT9h', 'FT9']",23,"['FFC3h', 'CPP5h', 'CCP5h', 'FFT7h', 'TP7', 'FFT9h', 'CP3', 'FC1', 'FC3', 'FC5', 'FTT9h', 'FCC5h', 'T7', 'C3', 'CCP3..."
15,sub-08,eyes_closed,7,"['FTT7h', 'O10', 'TTP7h', 'FT7', 'Fp1', 'T7', 'FC1']",17,"['C3', 'TP10', 'FFC3h', 'FC3', 'CCP5h', 'FFT7h', 'FFC5h', 'FCC3h', 'POO10h', 'AFp2', 'P10', 'C5', 'FC5', 'O2', 'FCC5..."
37,sub-20,eyes_closed,7,"['FC6', 'FFT7h', 'FFT8h', 'PO9', 'F8', 'FCC6h', 'PPO9h']",13,"['TP9', 'F2', 'PO7', 'O10', 'PO10', 'FFC2h', 'POO10h', 'O9', 'TP7', 'PPO10h', 'PO8', 'OI1h', 'POO9h']"
96,sub-52,eyes_open,7,"['FTT7h', 'AFp1', 'AFF6h', 'Fp2', 'FFT8h', 'Fp1', 'AF8']",12,"['FC6', 'F4', 'Fp2', 'FFC6h', 'FFT7h', 'FTT8h', 'Fp1', 'AFF5h', 'AF8', 'F5', 'FC5', 'T8']"
135,sub-73,eyes_closed,7,"['PO9', 'PPO9h', 'P9', 'O9', 'OI1h', 'POO9h', 'O1']",11,"['PO9', 'T7', 'TP9', 'OI1h', 'O9', 'O10', 'TP10', 'PO10', 'FTT10h', 'POO9h', 'PO7']"
125,sub-67,eyes_closed,7,"['T7', 'FFC5h', 'FFT7h', 'TPP10h', 'TP10', 'AF3', 'FT7']",4,"['AFF5h', 'FTT7h', 'F5', 'FTT8h']"
123,sub-66,eyes_closed,6,"['OI1h', 'P9', 'POO9h', 'P5', 'O1', 'PO7']",13,"['PO9', 'PPO9h', 'TP9', 'OI1h', 'O9', 'P9', 'PPO5h', 'POO1', 'POO9h', 'Oz', 'O1', 'PO7', 'FCC1h']"
126,sub-68,eyes_open,5,"['TP9', 'AFp1', 'PO8', 'AFp2', 'TPP7h']",28,"['AFF1h', 'FFC5h', 'TTP8h', 'F5', 'AF7', 'FFC6h', 'FTT9h', 'F3', 'AFF6h', 'CCP5h', 'FFT8h', 'Fp1', 'AFF5h', 'FCC5h',..."
62,sub-35,eyes_open,5,"['FC5', 'Fp2', 'F3', 'AF8', 'F10']",19,"['FFT8h', 'AFF6h', 'F6', 'FFC6h', 'FT8', 'FT10', 'AF4', 'F4', 'AF3', 'Fp2', 'AFp2', 'FFT10h', 'P7', 'FTT10h', 'F8', ..."
65,sub-36,eyes_closed,5,"['FTT7h', 'FTT8h', 'PO9', 'P9', 'FT9']",15,"['TP9', 'FFC5h', 'PO9', 'TTP7h', 'PPO9h', 'O9', 'POO9h', 'C5', 'O1', 'T8', 'PO7', 'FT10', 'T7', 'OI1h', 'P9']"
139,sub-75,eyes_closed,5,"['PPO9h', 'PO9', 'P9', 'O9', 'Oz']",13,"['OI1h', 'TP9', 'TPP9h', 'FCC5h', 'PPO10h', 'PO8', 'TP10', 'O2', 'POO10h', 'FC5', 'O1', 'PO7', 'FT7']"
90,sub-49,eyes_open,5,"['O10', 'C1', 'C4', 'C5', 'FC5']",12,"['FC6', 'Fp2', 'AF7', 'POz', 'F6', 'CCP5h', 'C6', 'FC4', 'Fp1', 'CCP2h', 'FCC6h', 'FCC5h']"
100,sub-54,eyes_open,5,"['AFp1', 'Fp2', 'AFp2', 'Fp1', 'FFT10h']",12,"['F9', 'P1', 'AFp1', 'TPP10h', 'Fp2', 'AF7', 'AFp2', 'Fp1', 'P10', 'AF8', 'FFT9h', 'F10']"

### ICA QC: top 20 rows by removed components

,subject_id,condition,method,n_components,eog_components,icalabel_components,excluded_components,n_excluded_components
95,sub-51,eyes_closed,fastica,120,"[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(11), np.int64(12), np.int64(...","[1, 5, 10, 14, 20, 21, 38, 41, 46, 48, 64, 83, 85, 97]","[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), 10, np.int64(11), np.int64(12), 14, 2...",21
39,sub-21,eyes_closed,fastica,125,"[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(7), np.int64(9), np.int64(11...","[3, 8, 12, 14, 15, 22, 24, 34, 71]","[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(7), 8, np.int64(9), np.int64...",19
7,sub-04,eyes_closed,fastica,120,"[np.int64(0), np.int64(1), np.int64(2), np.int64(8), np.int64(16), np.int64(44)]","[0, 2, 8, 18, 21, 28, 42, 48, 67, 73, 87, 93, 99, 106, 111, 119]","[np.int64(0), np.int64(1), np.int64(2), np.int64(8), np.int64(16), 18, 21, 28, 42, np.int64(44), 48, 67, 73, 87, 93,...",19
105,sub-57,eyes_closed,fastica,121,"[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(13), np.int64(23)]","[3, 9, 22, 27, 31, 46, 51, 58, 78, 97, 100, 112]","[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), 9, np.int64(13), 22, np.int64(23), 27, 31, 46, 51,...",18
2,sub-02,eyes_open,fastica,113,"[np.int64(0), np.int64(4), np.int64(11), np.int64(77), np.int64(83)]","[0, 1, 2, 7, 8, 10, 24, 31, 42, 59, 61, 79, 80, 100]","[np.int64(0), 1, 2, np.int64(4), 7, 8, 10, np.int64(11), 24, 31, 42, 59, 61, np.int64(77), 79, 80, np.int64(83), 100]",18
119,sub-64,eyes_closed,fastica,116,"[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(10), np.int64(12)]","[10, 18, 29, 45, 60, 62, 64, 82, 85, 89, 96]","[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(10), np.int64(12), 18, 29, 4...",18
123,sub-66,eyes_closed,fastica,113,"[np.int64(0), np.int64(1), np.int64(2), np.int64(4), np.int64(7), np.int64(14), np.int64(30)]","[0, 1, 4, 5, 40, 61, 80, 81, 82, 91, 95, 101, 111]","[np.int64(0), np.int64(1), np.int64(2), np.int64(4), 5, np.int64(7), np.int64(14), np.int64(30), 40, 61, 80, 81, 82,...",17
13,sub-07,eyes_closed,fastica,114,"[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(24)]","[0, 3, 22, 23, 25, 27, 28, 31, 34, 39, 49, 64]","[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), 22, 23, np.int64(24), 25, 27, 28, 31,...",17
37,sub-20,eyes_closed,fastica,110,"[np.int64(0), np.int64(1), np.int64(2), np.int64(4), np.int64(5), np.int64(7), np.int64(9), np.int64(28), np.int64(51)]","[1, 15, 25, 38, 54, 78, 80, 102]","[np.int64(0), np.int64(1), np.int64(2), np.int64(4), np.int64(5), np.int64(7), np.int64(9), 15, 25, np.int64(28), 38...",16
117,sub-63,eyes_closed,fastica,114,"[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(9), np.int64(10), np.int64(48), np.int64(...","[0, 1, 2, 53, 68, 74, 79, 86, 107, 111]","[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(9), np.int64(10), np.int64(48), 53, np.in...",16
137,sub-74,eyes_closed,fastica,119,"[np.int64(0), np.int64(1), np.int64(2), np.int64(4), np.int64(6), np.int64(13), np.int64(19), np.int64(71)]","[2, 6, 14, 27, 42, 55, 59, 73, 91, 114]","[np.int64(0), np.int64(1), np.int64(2), np.int64(4), np.int64(6), np.int64(13), 14, np.int64(19), 27, 42, 55, 59, np...",16
143,sub-77,eyes_closed,fastica,120,"[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(10), np.int64(3...","[1, 2, 5, 11, 30, 64, 90, 106, 113]","[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(10), 11, 30, np...",16
99,sub-53,eyes_closed,fastica,125,"[np.int64(0), np.int64(1), np.int64(2), np.int64(10), np.int64(73), np.int64(88)]","[0, 7, 14, 23, 52, 79, 85, 109, 112, 114, 123]","[np.int64(0), np.int64(1), np.int64(2), 7, np.int64(10), 14, 23, 52, np.int64(73), 79, 85, np.int64(88), 109, 112, 1...",16
61,sub-33,eyes_closed,fastica,126,"[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(10), np.int64(38)]","[0, 1, 6, 8, 13, 59, 86, 105, 109, 111, 114, 120]","[np.int64(0), np.int64(1), np.int64(2), np.int64(3), 6, 8, np.int64(10), 13, np.int64(38), 59, 86, 105, 109, 111, 11...",16
69,sub-38,eyes_closed,fastica,122,"[np.int64(0), np.int64(1), np.int64(2), np.int64(4), np.int64(6), np.int64(12), np.int64(20), np.int64(23)]","[0, 2, 9, 11, 12, 21, 35, 45, 49, 83, 84]","[np.int64(0), np.int64(1), np.int64(2), np.int64(4), np.int64(6), 9, 11, np.int64(12), np.int64(20), 21, np.int64(23...",16
109,sub-59,eyes_closed,fastica,114,"[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(6), np.int64(7), np.int64(9), np.int64(35...","[6, 32, 35, 48, 87, 101, 104]","[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(6), np.int64(7), np.int64(9), 32, np.int6...",15
130,sub-71,eyes_open,fastica,118,"[np.int64(0), np.int64(1), np.int64(2), np.int64(12)]","[0, 3, 5, 9, 16, 18, 20, 28, 30, 47, 67, 69]","[np.int64(0), np.int64(1), np.int64(2), 3, 5, 9, np.int64(12), 16, 18, 20, 28, 30, 47, 67, 69]",15
45,sub-24,eyes_closed,fastica,117,"[np.int64(0), np.int64(1), np.int64(2), np.int64(4), np.int64(6), np.int64(8), np.int64(9), np.int64(19), np.int64(20)]","[14, 19, 42, 81, 103, 110, 112]","[np.int64(0), np.int64(1), np.int64(2), np.int64(4), np.int64(6), np.int64(8), np.int64(9), 14, np.int64(19), np.int...",15
86,sub-47,eyes_open,fastica,118,"[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(6), np.int64(10)]","[2, 7, 19, 24, 53, 56, 59, 62, 78, 115]","[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(6), 7, np.int64(10), 19, 24, 53, 56, 59, 62, 78, 115]",15
68,sub-38,eyes_open,fastica,115,"[np.int64(0), np.int64(1), np.int64(3), np.int64(4), np.int64(6), np.int64(7)]","[0, 3, 5, 13, 21, 25, 26, 30, 33, 55, 73]","[np.int64(0), np.int64(1), np.int64(3), np.int64(4), 5, np.int64(6), np.int64(7), 13, 21, 25, 26, 30, 33, 55, 73]",15

### Epoch QC: top 20 rows by rejected epochs

,subject_id,condition,n_epochs_before_rejection,n_epochs_after_rejection,n_epochs_dropped,percent_epochs_dropped,excluded_bad_channels
128,sub-70,eyes_open,120,83,37,30.833333,"['CCP2h', 'F8']"
92,sub-50,eyes_open,120,85,35,29.166667,"[np.str_('F4'), np.str_('FCC4h'), np.str_('FFC6h'), 'FT9']"
101,sub-54,eyes_closed,180,135,45,25.000000,"[np.str_('AF8'), np.str_('T7')]"
141,sub-76,eyes_closed,180,148,32,17.777778,"[np.str_('FC5'), np.str_('FTT9h'), 'P9', 'TP9']"
129,sub-70,eyes_closed,180,158,22,12.222222,[]
64,sub-36,eyes_open,120,107,13,10.833333,"['AFp2', np.str_('F5'), np.str_('FFC5h'), np.str_('FT9'), 'P9', 'PO9', 'PPO9h', np.str_('TP10'), 'TP8', np.str_('TPP..."
65,sub-36,eyes_closed,180,165,15,8.333333,"[np.str_('FT9'), np.str_('FTT7h'), 'FTT8h', 'P9', 'PO9']"
38,sub-21,eyes_open,120,110,10,8.333333,[np.str_('FFT8h')]
50,sub-27,eyes_open,120,110,10,8.333333,"[np.str_('F10'), 'FC5', np.str_('FFT10h'), 'PO9']"
103,sub-56,eyes_closed,180,167,13,7.222222,['TPP10h']
140,sub-76,eyes_open,120,113,7,5.833333,"['FC4', 'P2', 'TP9']"
31,sub-16,eyes_closed,180,170,10,5.555556,[]
76,sub-42,eyes_open,120,115,5,4.166667,[]
102,sub-56,eyes_open,120,116,4,3.333333,[np.str_('FC6')]
73,sub-40,eyes_closed,180,174,6,3.333333,[]
84,sub-46,eyes_open,120,116,4,3.333333,[]
24,sub-13,eyes_open,120,116,4,3.333333,[]
145,sub-78,eyes_closed,180,175,5,2.777778,"['AFp2', 'P9', 'PPO9h']"
83,sub-45,eyes_closed,180,175,5,2.777778,[np.str_('PO10')]
36,sub-20,eyes_open,120,117,3,2.500000,[]

Full aggregate QC tables saved in: /Users/nataliemarryatt/neurogenetics-ml/data/processed/eeg